spring:
  datasource:
    url: jdbc:h2:mem:users
    generate-unique-name: false
    name: users
    username: "{cipher}f0e0577294e1af7be82d46daa975e3005c4a0f6c5a7f0b4a1c2e50bb518b0767"
    password: "{cipher}8db0d1db56bb729ebd0374d05e1a8fde432b711f6a5681e762ac94adfcd8faa9"
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh, info
  endpoint:
    health:
      probes:
        enabled: true

  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: User Service
    description: Allows users to register with QZ.
    owner: Beast Boy